[02/Jul/2016 16:24:36] ERROR [gunicorn.error:230] Exception in worker process:
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/accounts/admin.py", line 6, in <module>
    admin.site.unregister(Account)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
NotRegistered: The model Account is not registered
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/accounts/admin.py", line 6, in <module>
    admin.site.unregister(Account)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
NotRegistered: The model Account is not registered
[02/Jul/2016 16:24:36] ERROR [gunicorn.error:230] Exception in worker process:
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/accounts/admin.py", line 6, in <module>
    admin.site.unregister(Account)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
NotRegistered: The model Account is not registered
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/accounts/admin.py", line 6, in <module>
    admin.site.unregister(Account)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 123, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
NotRegistered: The model Account is not registered
[02/Jul/2016 16:24:36] INFO [gunicorn.error:224] Worker exiting (pid: 44863)
[02/Jul/2016 16:24:36] INFO [gunicorn.error:224] Worker exiting (pid: 44863)
[02/Jul/2016 16:26:15] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/main/settings/development.py modified
[02/Jul/2016 16:26:15] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/main/settings/development.py modified
[02/Jul/2016 16:26:15] INFO [gunicorn.error:224] Worker exiting (pid: 44870)
[02/Jul/2016 16:26:15] INFO [gunicorn.error:224] Worker exiting (pid: 44870)
[02/Jul/2016 16:26:24] ERROR [django.request:284] Internal Server Error: /admin/
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 374, in resolve
    for pattern in self.url_patterns:
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/urls.py", line 8, in <module>
    url('', include('social.apps.django_app.urls', namespace='social')),
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/social/apps/django_app/urls.py", line 10, in <module>
    from social.apps.django_app import views
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/social/apps/django_app/views.py", line 10, in <module>
    from social.apps.django_app.utils import psa
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 21, in <module>
    Storage = module_member(STORAGE)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/social/utils.py", line 56, in module_member
    module = import_module(mod)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/social/utils.py", line 50, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/social/apps/django_app/default/models.py", line 68, in <module>
    class UserSocialAuth(AbstractUserSocialAuth):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/models/base.py", line 102, in __new__
    "INSTALLED_APPS." % (module, name)
RuntimeError: Model class social.apps.django_app.default.models.UserSocialAuth doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
[02/Jul/2016 16:26:54] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/main/urls.py modified
[02/Jul/2016 16:26:54] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/main/urls.py modified
[02/Jul/2016 16:26:54] INFO [gunicorn.error:224] Worker exiting (pid: 44887)
[02/Jul/2016 16:26:54] INFO [gunicorn.error:224] Worker exiting (pid: 44887)
[02/Jul/2016 16:27:01] INFO [gunicorn.error:224] Worker exiting (pid: 44919)
[02/Jul/2016 16:27:01] INFO [gunicorn.error:224] Worker exiting (pid: 44919)
[02/Jul/2016 16:27:28] INFO [gunicorn.error:224] Worker exiting (pid: 44926)
[02/Jul/2016 16:27:28] INFO [gunicorn.error:224] Worker exiting (pid: 44926)
[02/Jul/2016 16:41:42] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/main/urls.py modified
[02/Jul/2016 16:41:42] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/main/urls.py modified
[02/Jul/2016 16:41:42] INFO [gunicorn.error:224] Worker exiting (pid: 44957)
[02/Jul/2016 16:41:42] INFO [gunicorn.error:224] Worker exiting (pid: 44957)
[02/Jul/2016 16:44:16] INFO [gunicorn.error:224] Worker exiting (pid: 45138)
[02/Jul/2016 16:44:16] INFO [gunicorn.error:224] Worker exiting (pid: 45138)
[02/Jul/2016 16:48:52] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/main/settings/development.py modified
[02/Jul/2016 16:48:52] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/main/settings/development.py modified
[02/Jul/2016 16:48:52] INFO [gunicorn.error:224] Worker exiting (pid: 45240)
[02/Jul/2016 16:48:52] INFO [gunicorn.error:224] Worker exiting (pid: 45240)
[02/Jul/2016 17:01:56] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py modified
[02/Jul/2016 17:01:56] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py modified
[02/Jul/2016 17:01:56] INFO [gunicorn.error:224] Worker exiting (pid: 45365)
[02/Jul/2016 17:01:56] INFO [gunicorn.error:224] Worker exiting (pid: 45365)
[02/Jul/2016 17:01:57] ERROR [gunicorn.error:230] Exception in worker process:
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 14, in <module>
    admin.site.register(Theme)
NameError: name 'Theme' is not defined
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 14, in <module>
    admin.site.register(Theme)
NameError: name 'Theme' is not defined
[02/Jul/2016 17:01:57] ERROR [gunicorn.error:230] Exception in worker process:
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 14, in <module>
    admin.site.register(Theme)
NameError: name 'Theme' is not defined
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 14, in <module>
    admin.site.register(Theme)
NameError: name 'Theme' is not defined
[02/Jul/2016 17:01:57] INFO [gunicorn.error:224] Worker exiting (pid: 45582)
[02/Jul/2016 17:01:57] INFO [gunicorn.error:224] Worker exiting (pid: 45582)
[02/Jul/2016 17:02:21] ERROR [django.request:284] Internal Server Error: /admin/vehicles/vehicle/
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 244, in inner
    return view(request, *args, **kwargs)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1470, in changelist_view
    self.list_max_show_all, self.list_editable, self)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 79, in __init__
    self.get_results(request)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/contrib/admin/views/main.py", line 174, in get_results
    result_count = paginator.count
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/paginator.py", line 72, in _get_count
    self._count = self.object_list.count()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/models/query.py", line 371, in count
    return self.query.get_count(using=self.db)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 483, in get_count
    number = obj.get_aggregation(using, ['__count'])['__count']
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/models/sql/query.py", line 464, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
ProgrammingError: (1146, "Table 'legend.vehicles_vehicle' doesn't exist")
[02/Jul/2016 17:02:26] INFO [gunicorn.error:224] Worker exiting (pid: 45590)
[02/Jul/2016 17:02:26] INFO [gunicorn.error:224] Worker exiting (pid: 45590)
[02/Jul/2016 17:27:32] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py modified
[02/Jul/2016 17:27:32] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py modified
[02/Jul/2016 17:27:32] INFO [gunicorn.error:224] Worker exiting (pid: 45602)
[02/Jul/2016 17:27:32] INFO [gunicorn.error:224] Worker exiting (pid: 45602)
[02/Jul/2016 17:27:34] ERROR [gunicorn.error:230] invalid syntax (models.py, line 3)
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 3
    from app.
            ^
SyntaxError: invalid syntax
[02/Jul/2016 17:27:34] ERROR [gunicorn.error:230] invalid syntax (models.py, line 3)
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 3
    from app.
            ^
SyntaxError: invalid syntax
[02/Jul/2016 17:28:15] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py modified
[02/Jul/2016 17:28:15] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py modified
[02/Jul/2016 17:28:15] INFO [gunicorn.error:224] Worker exiting (pid: 46012)
[02/Jul/2016 17:28:15] INFO [gunicorn.error:224] Worker exiting (pid: 46012)
[02/Jul/2016 17:28:16] ERROR [gunicorn.error:230] Exception in worker process:
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 3, in <module>
    from app.vehicle.models import Company
ImportError: No module named vehicle.models
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 3, in <module>
    from app.vehicle.models import Company
ImportError: No module named vehicle.models
[02/Jul/2016 17:28:16] ERROR [gunicorn.error:230] Exception in worker process:
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 3, in <module>
    from app.vehicle.models import Company
ImportError: No module named vehicle.models
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 3, in <module>
    from app.vehicle.models import Company
ImportError: No module named vehicle.models
[02/Jul/2016 17:28:16] INFO [gunicorn.error:224] Worker exiting (pid: 46019)
[02/Jul/2016 17:28:16] INFO [gunicorn.error:224] Worker exiting (pid: 46019)
[02/Jul/2016 17:29:11] ERROR [gunicorn.error:230] unexpected indent (models.py, line 18)
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 18
    address = models.CharField(max_length=200,unique=True)
    ^
IndentationError: unexpected indent
[02/Jul/2016 17:29:11] ERROR [gunicorn.error:230] unexpected indent (models.py, line 18)
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 18
    address = models.CharField(max_length=200,unique=True)
    ^
IndentationError: unexpected indent
[02/Jul/2016 17:29:26] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py modified
[02/Jul/2016 17:29:26] INFO [gunicorn.error:224] Worker reloading: /Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py modified
[02/Jul/2016 17:29:27] INFO [gunicorn.error:224] Worker exiting (pid: 46029)
[02/Jul/2016 17:29:27] INFO [gunicorn.error:224] Worker exiting (pid: 46029)
[02/Jul/2016 17:29:28] ERROR [gunicorn.error:230] unexpected indent (models.py, line 18)
Traceback (most recent call last):
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/main/wsgi.py", line 13, in <module>
    application = get_wsgi_application()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/Afxal/workspace/newenv/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/Afxal/workspace/freelancing/legendary-packers/app/vehicles/models.py", line 18
    address = models.CharField(max_length=200,unique=True)
    ^
IndentationError: unexpected indent
